/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Cliente_ctrl;

/**
 *
 * @author André Teixeira
 */
public class Cliente_view extends javax.swing.JFrame {

    Cliente_ctrl controle = new Cliente_ctrl();
    int cod_pesq;

    /**
     * Creates new form Cliente_view
     */
    public Cliente_view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_codigo = new javax.swing.JLabel();
        vlr_codigo = new javax.swing.JTextField();
        bt_pesquisa = new javax.swing.JButton();
        bt_primeiro = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();
        bt_avanca = new javax.swing.JButton();
        bt_ultimo = new javax.swing.JButton();
        txt_nome = new javax.swing.JLabel();
        vlr_nome = new javax.swing.JTextField();
        txt_sexo = new javax.swing.JLabel();
        cb_sexo = new javax.swing.JComboBox<>();
        bt_novo = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");

        txt_codigo.setText("Codigo");

        vlr_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vlr_codigoFocusLost(evt);
            }
        });

        bt_pesquisa.setText("?");
        bt_pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_pesquisaMouseClicked(evt);
            }
        });

        bt_primeiro.setText("<<");
        bt_primeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_primeiroMouseClicked(evt);
            }
        });

        bt_voltar.setText("<");
        bt_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_voltarMouseClicked(evt);
            }
        });

        bt_avanca.setText(">");
        bt_avanca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_avancaMouseClicked(evt);
            }
        });

        bt_ultimo.setText(">>");
        bt_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ultimoMouseClicked(evt);
            }
        });

        txt_nome.setText("Nome");

        vlr_nome.setEnabled(false);

        txt_sexo.setText("Sexo");

        cb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        cb_sexo.setEnabled(false);

        bt_novo.setText("Novo");
        bt_novo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_novoMouseClicked(evt);
            }
        });

        bt_salvar.setText("Salvar");
        bt_salvar.setEnabled(false);
        bt_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_salvarMouseClicked(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.setEnabled(false);
        bt_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cancelarMouseClicked(evt);
            }
        });

        bt_excluir.setText("Excluir");
        bt_excluir.setEnabled(false);
        bt_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_excluirMouseClicked(evt);
            }
        });

        bt_editar.setText("Editar");
        bt_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_editarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt_sexo)
                            .addGap(10, 10, 10)
                            .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(vlr_nome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(vlr_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bt_pesquisa))
                                .addComponent(txt_nome))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_avanca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_salvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vlr_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_pesquisa)
                        .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_avanca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_primeiro)
                    .addComponent(bt_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vlr_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_salvar))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_sexo)
                        .addComponent(bt_cancelar))
                    .addComponent(txt_sexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_excluir)
                    .addComponent(bt_editar)
                    .addComponent(bt_novo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vlr_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vlr_codigoFocusLost
        if (!vlr_codigo.getText().equals("")) {
            String[] resultado;
            resultado = controle.recuperar(Integer.parseInt(vlr_codigo.getText()));

            vlr_codigo.setText(String.valueOf(resultado[0]));
            vlr_nome.setText(resultado[1]);
            cb_sexo.setSelectedItem(resultado[2]);
        }
    }//GEN-LAST:event_vlr_codigoFocusLost

    private void bt_novoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_novoMouseClicked
        limpaTela();
        vlr_codigo.setText("0");
        vlr_nome.requestFocus();
        ativa(true);
        bt_excluir.setEnabled(false);
    }//GEN-LAST:event_bt_novoMouseClicked

    private void bt_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salvarMouseClicked
        String[] Cliente = new String[3];
        Cliente[0] = vlr_codigo.getText();
        Cliente[1] = vlr_nome.getText();
        Cliente[2] = (String) cb_sexo.getSelectedItem();

        controle.salvar(Cliente);
        
        limpaTela();
        ativa(false);
    }//GEN-LAST:event_bt_salvarMouseClicked

    private void bt_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cancelarMouseClicked
        limpaTela();
        ativa(false);
    }//GEN-LAST:event_bt_cancelarMouseClicked

    private void bt_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_voltarMouseClicked
        int cod = Integer.parseInt(vlr_codigo.getText()) - 1;
        if (cod >= 1) {
            vlr_codigo.setText(String.valueOf(cod));
            vlr_codigo.requestFocus();
            bt_voltar.requestFocus();
        }
    }//GEN-LAST:event_bt_voltarMouseClicked

    private void bt_avancaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_avancaMouseClicked
        int cod = Integer.parseInt(vlr_codigo.getText()) + 1;
        if (cod >= 1) {
            vlr_codigo.setText(String.valueOf(cod));
            vlr_codigo.requestFocus();
            bt_voltar.requestFocus();
        }
    }//GEN-LAST:event_bt_avancaMouseClicked

    private void bt_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ultimoMouseClicked
        String[] cliente = controle.recuperaUltimo();

        vlr_codigo.setText(cliente[0]);
        vlr_nome.setText(cliente[1]);
        cb_sexo.setSelectedItem(cliente[2]);
    }//GEN-LAST:event_bt_ultimoMouseClicked

    private void bt_primeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_primeiroMouseClicked
        String[] cliente = controle.recuperaPrimeiro();

        vlr_codigo.setText(cliente[0]);
        vlr_nome.setText(cliente[1]);
        cb_sexo.setSelectedItem(cliente[2]);
    }//GEN-LAST:event_bt_primeiroMouseClicked

    private void bt_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_editarMouseClicked
        String cod = vlr_codigo.getText();
        
        if ( !cod.equals("0") && !cod.equals("")) {
            ativa(true);
        }
    }//GEN-LAST:event_bt_editarMouseClicked

    private void bt_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_excluirMouseClicked
        String cod = vlr_codigo.getText();
        if ( !cod.equals("0") && !cod.equals("")) {
            controle.excluir(Integer.parseInt(cod));
            ativa(false);
            limpaTela();
        }
    }//GEN-LAST:event_bt_excluirMouseClicked

    private void bt_pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pesquisaMouseClicked
        Pesquisa_Cliente_View frame = new Pesquisa_Cliente_View();
        frame.setVisible(true);
    }//GEN-LAST:event_bt_pesquisaMouseClicked

    public void ativa(boolean ativo) {
        vlr_codigo.setEnabled(!ativo);
        vlr_nome.setEnabled(ativo);
        cb_sexo.setEnabled(ativo);

        bt_pesquisa.setEnabled(!ativo);

        bt_primeiro.setEnabled(!ativo);
        bt_ultimo.setEnabled(!ativo);
        bt_voltar.setEnabled(!ativo);
        bt_avanca.setEnabled(!ativo);

        bt_editar.setEnabled(!ativo);
        bt_novo.setEnabled(!ativo);

        bt_excluir.setEnabled(ativo);
        bt_salvar.setEnabled(ativo);
        bt_cancelar.setEnabled(ativo);
    }
    
    public void limpaTela(){
        vlr_codigo.setText("");
        vlr_nome.setText("");
        cb_sexo.setSelectedIndex(-1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_avanca;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_pesquisa;
    private javax.swing.JButton bt_primeiro;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton bt_ultimo;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JComboBox<String> cb_sexo;
    private javax.swing.JLabel txt_codigo;
    private javax.swing.JLabel txt_nome;
    private javax.swing.JLabel txt_sexo;
    private javax.swing.JTextField vlr_codigo;
    private javax.swing.JTextField vlr_nome;
    // End of variables declaration//GEN-END:variables
}
